### ISSUE TITLE
Official release and version number missing

### ISSUE THREAD

**Issue by thomask77** [slusarz/dovecot-fts-flatcurve#1]
Hi!

I saw that fts-flatcurve is recommended in the official Dovecot manual:

* https://doc.dovecot.org/configuration_manual/fts/

Is this project ready to use yet?
Seems to be very new, and I can't find anyone using it..

I would like to package it for NixOS so a version number would be nice.

**Comment by slusarz** [comment]
Hi!

You are correct - the plan is that flatcurve will eventually move into Dovecot core and become the default FTS option for CE.  Hopefully enabled by default, since we are lacking a stable, standalone FTS option at the moment.

However, the code will essentially change ownership at that point.  The Engineering team will be free to make whatever changes they deem necessary to incorporate into core.  Hopefully, any changes will be minimal, but it is a potential risk.

That being said, there are multiple people I personally know using flatcurve (beta testing, essentially) and it seems to work for day-to-day usage.  At a minimum, it doesn't crash or cause any issues, so it is safe enough to be used more widely in my opinion.

I have no issue with "officially" tagging/releasing a version so that it can be packaged elsewhere.  I spent a bit of time putting together some automated github automated testing, so once that passes I will release.

**Comment by slusarz** [comment]
v0.1.0 has been released.
