### ISSUE TITLE
Feature Request: Change Flatcurve Index Location via config parameter

### ISSUE THREAD

**Issue by DerLinkman** [slusarz/dovecot-fts-flatcurve#33]
Hi everyone,

very nice Plugin/FTS you wrote with flatcurve here so thanks for that. It works like a charm so far :)

But i have a question or a feature request if this is possible through flatcurve:
The ability to change the flatcurve (not the dovecot index) folder which is located (per default) at the dovecot index folder which is fine so far.

It would be nice if you could swap out the flat curve indexes. E.g. to a faster disk without being bound to the Dovecot own index.
Is this already possible and I have overlooked it? Or would that be a change to the Flatcurve plugin? (Is that even possible?)

Thanks for your answer :)

**Comment by slusarz** [comment]
Flatcurve relies on Dovecot's core API to place index files, so we are limited to what is provided by that API.  Namely: https://doc.dovecot.org/configuration_manual/mail_location/#mail-location-settings

FTS data is considered a "Dovecot index file", because most changes to index files will also alter FTS indexes.  So it doesn't generally make much sense to separate those two.  The key distinction is between static data (mail blobs) and metadata (indexes).

Obviously, you can alter the source however you like if you disagree.  But this isn't going to be something that is added.
