### ISSUE TITLE
QA: Differences to fts -xapian

### ISSUE THREAD

**Issue by mstilkerich** [slusarz/dovecot-fts-flatcurve#4]
Hello,

  from a user perspective, I wonder what the differences of this fts plugin vs fts-xapian are, so I could decide which one to use. From the available docs, it seems both do the same. I‘m currently using fts-xapian simply because this plugin requires a newer dovecot than available in Ubuntu. Still I wonder what motivated you to write a new plugin although fts xapian has been available for a while. I think it would be worthwhile to highlight the user relevant differences in the readme to aid new users in deciding which plugin to use.

**Comment by thomask77** [comment]
I also wondered the same.. the only reason, I got to fts-flatcurve was, that I never got fts-xapian to work without leaking memory or encountering some other crash bugs.

fts-flatcurve just works.

**Comment by slusarz** [comment]
I appreciate the question, but I'd rather the documentation focus on the features that fts-flatcurve has rather than turning this into some sort of competition or direct comparison.
This becomes largely irrelevant in the (hopefully) new future, as the current plan is to fold fts-flatcurve into Dovecot core so that it becomes the default, works out-of-the-box FTS engine (which is currently missing - all existing FTS drivers either require a 3rd party service or are deprecated).
That being said, a brief list of reasons why I originally created fts-flatcurve:

- To address the aforementioned problem that Dovecot CE does not have a default FTS solution that works out-of-the box
- Create a driver that uses an actively developed search library (xapian), as opposed to old, abandoned libraries (e.g. lucene)
- fts-xapian would be an option, but there were multiple issues:
  - It was buggy and crashed a bunch when I was testing. (I have no idea if I was using it wrong, or if things have improved, but that was my experience when I evaluated it)
  - It did not correctly pass the IMAP stress test; i.e. it was not returning RFC compliant results
  - There was complicated stemming support it was trying to do.  There is no need to reinvent this - Dovecot already provides this within core
  - It was not using the new Dovecot events framework for logging/debugging/statistics
- Finally, I had to cancel an 11 day vacation at the end of March last year (...for reasons), and there was really nothing else to do in life, so I had to fill my time with something

Hope that gives some insight.  I'll leave this info here, but I don't see a need to put any of this into the README, so I will close the ticket.
