### ISSUE TITLE
Duplicate plugins

### ISSUE THREAD

**Issue by grosjo** [slusarz/dovecot-fts-flatcurve#5]
Hi @slusarz 
I am the developer of the Xapian plugin for Dovecot ( https://github.com/grosjo/fts-xapian )

We are doing duplicate work

My plugins is already pushed to Archlinux, Debian, and very soon Fedora

Shall we combine our efforts ?

**Comment by slusarz** [comment]
Hi @grosjo,

Thanks for your message.

I would respectfully disagree that we are doing duplicate work.  Yes, we are both using Xapian.  But I think our development strategies and goals are different.

I was already asked about the differences between the two plugins, and commented about it here: https://github.com/slusarz/dovecot-fts-flatcurve/issues/4#issuecomment-902425597.

The main design goal differences I see is that your code (or at least the last time I looked) is doing several things that are already handled by Dovecot core functionality (e.g. stemming).  Additionally, your configuration recommends a large amount of vsz memory in order to do indexing.

Flatcurve's design goal was to be integrated with Dovecot core as much as possible.  Additional, flatcurve's expectation is that indexing may be done on much smaller servers, so a big design goal was to limit the amount of memory required - it should work in almost all cases with < 256 MB - and there has been much work done regarding things like database sharding to facilitate this.

I am open to discussion surrounding my observations.  And I would gladly welcome any conversation or suggestions surrounding the best way of using Xapian with Dovecot, as you obviously have much experience in that area.  However, my conclusion is that our two projects are ... different.  And that's perfectly ok.  Choice is good, especially since the feature set - outside of the high-level of which indexing service is being developed against - is not the same.
